config/routes.rb
Rails.application.routes.draw do
  resources :wishes

   root 'application#hello'

end

app/models/wish.rb
class Wish < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def hello
    render text: 'hello world!'
  end
end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController
  before_action :set_wish, only: [:show, :edit, :update, :destroy]

  # GET /wishes
  # GET /wishes.json
  def index
    @wishes = Wish.all
  end

  # GET /wishes/1
  # GET /wishes/1.json
  def show
  end

  # GET /wishes/new
  def new
    @wish = Wish.new
  end

  # GET /wishes/1/edit
  def edit
  end

  # POST /wishes
  # POST /wishes.json
  def create
    @wish = Wish.new(wish_params)

    respond_to do |format|
      if @wish.save
        format.html { redirect_to @wish, notice: 'Wish was successfully created.' }
        format.json { render :show, status: :created, location: @wish }
      else
        format.html { render :new }
        format.json { render json: @wish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wishes/1
  # PATCH/PUT /wishes/1.json
  def update
    respond_to do |format|
      if @wish.update(wish_params)
        format.html { redirect_to @wish, notice: 'Wish was successfully updated.' }
        format.json { render :show, status: :ok, location: @wish }
      else
        format.html { render :edit }
        format.json { render json: @wish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wishes/1
  # DELETE /wishes/1.json
  def destroy
    @wish.destroy
    respond_to do |format|
      format.html { redirect_to wishes_url, notice: 'Wish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wish
      @wish = Wish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wish_params
      params.require(:wish).permit(:item, :color, :brand, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wishes_helper.rb
module WishesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WishList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/wishes/_form.html.erb
<%= form_for(@wish) do |f| %>
  <% if @wish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wish.errors.count, "error") %> prohibited this wish from being saved:</h2>

      <ul>
      <% @wish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item %><br>
    <%= f.text_field :item %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :brand %><br>
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wishes/edit.html.erb
<h1>Editing wish</h1>

<%= render 'form' %>

<%= link_to 'Show', @wish %> |
<%= link_to 'Back', wishes_path %>

app/views/wishes/index.html.erb
<h1>Listing wishes</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Color</th>
      <th>Brand</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wishes.each do |wish| %>
      <tr>
        <td><%= wish.item %></td>
        <td><%= wish.color %></td>
        <td><%= wish.brand %></td>
        <td><%= wish.picture %></td>
        <td><%= link_to 'Show', wish %></td>
        <td><%= link_to 'Edit', edit_wish_path(wish) %></td>
        <td><%= link_to 'Destroy', wish, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wish', new_wish_path %>

app/views/wishes/new.html.erb
<h1>New wish</h1>

<%= render 'form' %>

<%= link_to 'Back', wishes_path %>

app/views/wishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @wish.item %>
</p>

<p>
  <strong>Color:</strong>
  <%= @wish.color %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @wish.brand %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @wish.picture %>
</p>

<%= link_to 'Edit', edit_wish_path(@wish) %> |
<%= link_to 'Back', wishes_path %>